name: neusci490
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.23.3
  - scipy=1.9.3
  - matplotlib=3.6
  - scikit-learn
  - notebook
  - nb_conda_kernels
  - pip:
    - ipykernel
    - ipywidgets